package view;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import util.Utils;

/**
 * @author Cesardl
 */
public class JFrameInit extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public JFrameInit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        panelAlumno = new view.JPanelStudent();
        panelProfesor = new view.JPanelTeacher();
        menuBar = new javax.swing.JMenuBar();
        menuActions = new javax.swing.JMenu();
        menuAlumno = new javax.swing.JMenu();
        menuItemInsertAlumno = new javax.swing.JMenuItem();
        menuItemUpdateAlumno = new javax.swing.JMenuItem();
        menuItemDeleteAlumno = new javax.swing.JMenuItem();
        menuProfesor = new javax.swing.JMenu();
        menuItemInsertProfesor = new javax.swing.JMenuItem();
        menuItemUpdateProfesor = new javax.swing.JMenuItem();
        menuItemDeleteProfesor = new javax.swing.JMenuItem();
        separator = new javax.swing.JPopupMenu.Separator();
        menuItemExit = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        bundle = java.util.ResourceBundle.getBundle("view/Bundle"); // NOI18N
        setTitle(bundle.getString("app.title")); // NOI18N

        panel.setBackground(new java.awt.Color(255, 255, 255));

        tabbedPane.addTab(bundle.getString("dictionary.student"), panelAlumno); // NOI18N
        tabbedPane.addTab(bundle.getString("dictionary.teacher"), panelProfesor); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuBar.setBackground(new java.awt.Color(255, 255, 255));

        menuActions.setText(bundle.getString("dictionary.actions")); // NOI18N

        menuAlumno.setText(bundle.getString("dictionary.student")); // NOI18N

        menuItemInsertAlumno.setText(bundle.getString("dictionary.new")); // NOI18N
        menuItemInsertAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInsertAlumnoActionPerformed(evt);
            }
        });
        menuAlumno.add(menuItemInsertAlumno);

        menuItemUpdateAlumno.setText(bundle.getString("dictionary.edit")); // NOI18N
        menuItemUpdateAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUpdateAlumnoActionPerformed(evt);
            }
        });
        menuAlumno.add(menuItemUpdateAlumno);

        menuItemDeleteAlumno.setText(bundle.getString("dictionary.delete")); // NOI18N
        menuItemDeleteAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDeleteAlumnoActionPerformed(evt);
            }
        });
        menuAlumno.add(menuItemDeleteAlumno);

        menuActions.add(menuAlumno);

        menuProfesor.setText(bundle.getString("dictionary.teacher")); // NOI18N

        menuItemInsertProfesor.setText(bundle.getString("dictionary.new")); // NOI18N
        menuItemInsertProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInsertProfesorActionPerformed(evt);
            }
        });
        menuProfesor.add(menuItemInsertProfesor);

        menuItemUpdateProfesor.setText(bundle.getString("dictionary.edit")); // NOI18N
        menuItemUpdateProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUpdateProfesorActionPerformed(evt);
            }
        });
        menuProfesor.add(menuItemUpdateProfesor);

        menuItemDeleteProfesor.setText(bundle.getString("dictionary.delete")); // NOI18N
        menuItemDeleteProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDeleteProfesorActionPerformed(evt);
            }
        });
        menuProfesor.add(menuItemDeleteProfesor);

        menuActions.add(menuProfesor);
        menuActions.add(separator);

        menuItemExit.setText(bundle.getString("dictionary.exit")); // NOI18N
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuActions.add(menuItemExit);

        menuBar.add(menuActions);

        menuHelp.setText(bundle.getString("dictionary.help")); // NOI18N

        menuItemAbout.setText(bundle.getString("dictionary.about")); // NOI18N
        menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAboutActionPerformed(evt);
            }
        });
        menuHelp.add(menuItemAbout);

        menuBar.add(menuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemInsertAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInsertAlumnoActionPerformed
        panelAlumno.showDialog();
    }//GEN-LAST:event_menuItemInsertAlumnoActionPerformed

    private void menuItemUpdateAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUpdateAlumnoActionPerformed
        JTable target = panelAlumno.getTable();
        int row = target.getSelectedRow();

        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, bundle.getString("app.warning.student.table"), this.getTitle(), JOptionPane.WARNING_MESSAGE);
        } else {
            String code = String.valueOf(target.getValueAt(row, 0));

            tabbedPane.setSelectedIndex(0);

            panelAlumno.showDialog(row, code);
        }
    }//GEN-LAST:event_menuItemUpdateAlumnoActionPerformed

    private void menuItemDeleteAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDeleteAlumnoActionPerformed
        JTable target = panelAlumno.getTable();
        int row = target.getSelectedRow();

        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, bundle.getString("app.warning.student.table"), this.getTitle(), JOptionPane.WARNING_MESSAGE);
        } else {
            String code = String.valueOf(target.getValueAt(row, 0));

            int i = javax.swing.JOptionPane.showConfirmDialog(this, bundle.getString("app.warning.student.delete"),
                    this.getTitle(), javax.swing.JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                panelAlumno.deleteRow(row, code);
            }
        }
    }//GEN-LAST:event_menuItemDeleteAlumnoActionPerformed

    private void menuItemInsertProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInsertProfesorActionPerformed
        panelProfesor.showDialog();
    }//GEN-LAST:event_menuItemInsertProfesorActionPerformed

    private void menuItemUpdateProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUpdateProfesorActionPerformed
        JTable target = panelProfesor.getTable();
        int row = target.getSelectedRow();

        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, bundle.getString("app.warning.teacher.table"), this.getTitle(), JOptionPane.WARNING_MESSAGE);
        } else {
            String code = String.valueOf(target.getValueAt(row, 0));

            tabbedPane.setSelectedIndex(1);

            panelProfesor.showDialog(row, code);
        }
    }//GEN-LAST:event_menuItemUpdateProfesorActionPerformed

    private void menuItemDeleteProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDeleteProfesorActionPerformed
        JTable target = panelProfesor.getTable();
        int row = target.getSelectedRow();

        if (row == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, bundle.getString("app.warning.teacher.table"), this.getTitle(), JOptionPane.WARNING_MESSAGE);
        } else {
            String code = String.valueOf(target.getValueAt(row, 0));

            int i = javax.swing.JOptionPane.showConfirmDialog(this, bundle.getString("app.warning.teacher.delete"),
                    this.getTitle(), javax.swing.JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                panelProfesor.deleteRow(row, code);
            }
        }
    }//GEN-LAST:event_menuItemDeleteProfesorActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        int i = javax.swing.JOptionPane.showConfirmDialog(this, bundle.getString("app.warning.exit"),
                this.getTitle(), javax.swing.JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        JDialogAbout dialog = new JDialogAbout(this);
        Utils.installEscapeCloseOperation(dialog);
        Utils.installEnterCloseOperation(dialog);
        dialog.setVisible(true);
    }//GEN-LAST:event_menuItemAboutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuActions;
    private javax.swing.JMenu menuAlumno;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemDeleteAlumno;
    private javax.swing.JMenuItem menuItemDeleteProfesor;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemInsertAlumno;
    private javax.swing.JMenuItem menuItemInsertProfesor;
    private javax.swing.JMenuItem menuItemUpdateAlumno;
    private javax.swing.JMenuItem menuItemUpdateProfesor;
    private javax.swing.JMenu menuProfesor;
    private javax.swing.JPanel panel;
    private view.JPanelStudent panelAlumno;
    private view.JPanelTeacher panelProfesor;
    private javax.swing.JPopupMenu.Separator separator;
    private javax.swing.JTabbedPane tabbedPane;
    private java.util.ResourceBundle bundle;
    // End of variables declaration//GEN-END:variables
}
