/*
 * JPanelProfesor.java
 *
 * Created on 21/03/2010, 10:10:27 PM
 */
package view;

import beans.Profesor;
import controller.DialogAction;
import controller.ProfesorController;
import controller.impl.ProfesorControllerImpl;
import java.awt.Frame;
import javax.swing.JTable;
import util.Utils;

/**
 *
 * @author cesardl
 */
public class JPanelProfesor extends javax.swing.JPanel {

    private final ProfesorController profesorController = new ProfesorControllerImpl();

    /**
     * Creates new form JPanelProfesor
     */
    public JPanelProfesor() {
        initComponents();
    }

    /**
     *
     * @return
     */
    public JTable getTable() {
        return table;
    }

    public void addRow(Profesor profesor) {
        tableModel.addRow(new Object[]{
            profesor.getCodigo(),
            profesor.getNombre(),
            Utils.formatDate(profesor.getNacimiento()),
            profesor.getEmail()
        });
    }

    /**
     *
     * @param row
     * @param profesor
     */
    public void setRowValues(int row, Profesor profesor) {
        tableModel.setValueAt(profesor.getCodigo(), row, 0);
        tableModel.setValueAt(profesor.getNombre(), row, 1);
        tableModel.setValueAt(Utils.formatDate(profesor.getNacimiento()), row, 2);
        tableModel.setValueAt(profesor.getEmail(), row, 3);
    }

    /**
     *
     * @param parent
     * @param row
     * @param code
     */
    public void showDialogForUpdate(Frame parent, int row, String code) {
        Profesor profesor = profesorController.getByCode(code);

        JDialogProfesor dialogProfesor = new JDialogProfesor(parent, true);
        Utils.installEscapeCloseOperation(dialogProfesor);
        dialogProfesor.setProfesor(profesor);
        dialogProfesor.setVisible(true);

        profesor = dialogProfesor.getProfesor();

        DialogAction action = dialogProfesor.getAction();
        if (action != null && dialogProfesor.getAction().equals(DialogAction.UPDATE)) {
            setRowValues(row, profesor);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        tableModel = new javax.swing.table.DefaultTableModel(
            profesorController.getAll(),
            new String [] {
                "Codigo", "Nombre", "Nacimiento", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        setBackground(new java.awt.Color(255, 255, 255));

        table.setModel(tableModel);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable table;
    private javax.swing.table.DefaultTableModel tableModel;
    // End of variables declaration//GEN-END:variables
}
