/*
 * JPanelTeacher.java
 *
 * Created on 21/03/2010, 10:10:27 PM
 */
package view;

import beans.Teacher;
import controller.DialogAction;
import controller.TeacherController;
import controller.impl.TeacherControllerImpl;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import view.etc.JPanelBase;

/**
 *
 * @author Cesardl
 */
public class JPanelTeacher extends JPanelBase<Teacher> {

    private static final long serialVersionUID = -2833586888123947842L;

    private final TeacherController teacherController = new TeacherControllerImpl();

    /**
     * Creates new form JPanelTeacher.
     */
    public JPanelTeacher() {
        initComponents();
    }

    /**
     *
     * @return the table.
     */
    public JTable getTable() {
        return table;
    }

    @Override
    protected void addRow(Teacher entity) {
        tableModel.addRow(new Object[]{
            entity.getCode(),
            entity.getNames(),
            dateFormatHelper.formatDate(entity.getBirthday()),
            entity.getEmail()
        });
    }

    @Override
    protected void setRowValues(int row, Teacher entity) {
        tableModel.setValueAt(entity.getCode(), row, 0);
        tableModel.setValueAt(entity.getNames(), row, 1);
        tableModel.setValueAt(dateFormatHelper.formatDate(entity.getBirthday()), row, 2);
        tableModel.setValueAt(entity.getEmail(), row, 3);
    }

    @Override
    protected void deleteRow(int row, String code) {
        int i = JOptionPane.showConfirmDialog(this,
                resourceBundleHelper.getString("app.warning.teacher.delete"),
                resourceBundleHelper.getString("app.title"), JOptionPane.YES_NO_OPTION);

        if (i == JOptionPane.YES_OPTION) {
            boolean state = teacherController.delete(code);
            if (state) {
                tableModel.removeRow(row);
            }
        }
    }

    @Override
    public void showDialog(DialogAction dialogAction, int row, String code) {
        if (DialogAction.UPDATE.equals(dialogAction) && (row == BAD_ROW || code == null)) {
            throw new UnsupportedOperationException("You can not perform this action");
        }

        JDialogTeacher dialogTeacher = new JDialogTeacher(getParentForDialog());
        dialogTeacher.installEscapeCloseOperation();

        Teacher teacher;

        if (DialogAction.UPDATE.equals(dialogAction)) {
            teacher = teacherController.getByCode(code);
            dialogTeacher.setEntity(teacher);
        }

        dialogTeacher.setVisible(true);

        teacher = dialogTeacher.getEntity();
        if (teacher == null) {
            return;
        }

        switch (dialogAction) {
            case INSERT:
                addRow(teacher);
                break;

            case UPDATE:
                setRowValues(row, teacher);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        tableModel = new javax.swing.table.DefaultTableModel(
            teacherController.getAll(),
            new String [] {
                resourceBundleHelper.getString("dictionary.code"), resourceBundleHelper.getString("dictionary.names"), resourceBundleHelper.getString("dictionary.birthday"), resourceBundleHelper
                    .getString("dictionary.email")
            }
        ) {
            private static final long serialVersionUID = -6723620777953415621L;

            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };

        setBackground(new java.awt.Color(255, 255, 255));

        table.setModel(tableModel);
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableMousePressed(evt);
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableKeyPressed(evt);
            }
        });
        scrollPane.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMousePressed
        showDialogFromTable(evt);
    }//GEN-LAST:event_tableMousePressed

    private void tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyPressed
        deleteFromTable(evt);
    }//GEN-LAST:event_tableKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable table;
    private javax.swing.table.DefaultTableModel tableModel;
    // End of variables declaration//GEN-END:variables
}
